### ISSUE TITLE
Implementar consulta por Checkout

### ISSUE THREAD

**Issue by brunokarpo** [ManutencaoSoftwareUFG20161/java#3]
Disponibilizar uma interface REST para responder a requisição de consulta por de Checkout:

https://pagseguro.uol.com.br/v2/guia-de-integracao/tutorial-da-biblioteca-pagseguro-em-java.html#consultas

**Comment by augustoefr** [comment]
Bruno, revisa ai, por favor

**Comment by brunokarpo** [comment]
Tem um erro Augusto. Faltou fechar o try antes de declarar o Catch. Corrige, por favor.

**Comment by augustoefr** [comment]
Pronto. Veja se ficou bão!

**Comment by brunokarpo** [comment]
Pronto. Manda vê
