### ISSUE TITLE
Implementar consulta por código de transação

### ISSUE THREAD

**Issue by brunokarpo** [ManutencaoSoftwareUFG20161/java#4]
Disponibilizar uma interface REST para responder a requisição de consulta por código de transação, explicada em:

https://pagseguro.uol.com.br/v2/guia-de-integracao/tutorial-da-biblioteca-pagseguro-em-java.html#consultas

**Comment by DeafPenguin** [comment]
Passando para o Bruno

**Comment by brunokarpo** [comment]
Tá beleza.
