### ISSUE TITLE
Implementar consultas por intervalo de datas

### ISSUE THREAD

**Issue by brunokarpo** [ManutencaoSoftwareUFG20161/java#5]
Disponibilizar uma interface REST para responder a requisição de consulta por intervalo de datas, explicada em:

https://pagseguro.uol.com.br/v2/guia-de-integracao/tutorial-da-biblioteca-pagseguro-em-java.html#consultas

**Comment by matheus-gomes** [comment]
Revisa aí Bruno.

**Comment by brunokarpo** [comment]
Revisado e Ok
